# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      GRADLE_OPTS: "-Dorg.gradle.daemon=true -Dorg.gradle.parallel=true"
      TERM: dumb

    steps:
      - checkout

      - setup_remote_docker:
          version: 19.03.13

      - run:
          name: Build Docker image
          command: docker build -t spring-vertx-gradle-in-docker:$CIRCLE_BRANCH .
          when: on_success

      - run:
          name: Start application in the Docker container
          command: docker run -d -p 8080:8080 --name the-app spring-vertx-gradle-in-docker:$CIRCLE_BRANCH
          when: on_success

      - run:
          name: Waiting for the application to start
          command: sleep 5
          when: on_success

      - run:
          name: List Docker containers as a sanity check
          command: docker ps
          when: on_success

      - run:
          name: Inspect running Docker container
          command: docker inspect the-app
          when: on_success

      - run:
          name: cURL /api/v1/health/ping using a GET request
          command: docker exec the-app curl -s --retry 10 --retry-connrefused http://localhost:8080/api/v1/health/ping
          when: on_success
